"""
============================================================
FILE: query_executor.py
LOCATION: backend/app/ai/query_executor.py
============================================================

PURPOSE
-------
Execute validated AI-generated SQL against a dataset.

The AI always generates SQL using a logical table name:

    dataset

This module maps that logical table name to the real
Parquet dataset by creating a temporary DuckDB view.

PIPELINE POSITION
-----------------

Natural language question
        ↓
LLM generates SQL
        ↓
SQL safety validation
        ↓
DuckDB semantic validation
        ↓
EXECUTE SQL (this module)
        ↓
Return results to API

============================================================
"""

from __future__ import annotations

import duckdb


# ============================================================
# EXECUTE SQL QUERY
# ============================================================

def execute_sql_query(
    sql: str,
    dataset_name: str,
    dataset_source_path_fn,
    limit: int = 200,
):
    """
    Execute validated SQL against the dataset using DuckDB.

    Parameters
    ----------
    sql
        SQL generated by the AI.

    dataset_name
        Dataset identifier from the API request.

    dataset_source_path_fn
        Function that resolves dataset name → Parquet path.

    limit
        Maximum preview rows returned to the UI.
    """

    # --------------------------------------------------------
    # STEP 1 — Resolve dataset file path
    # --------------------------------------------------------

    src, _is_glob = dataset_source_path_fn(dataset_name)

    esc = src.replace("'", "''")

    # --------------------------------------------------------
    # STEP 2 — Open DuckDB connection
    # --------------------------------------------------------

    con = duckdb.connect()

    try:

        # ----------------------------------------------------
        # STEP 3 — Register logical table "dataset"
        # ----------------------------------------------------
        # This allows the AI SQL to reference the table
        # exactly as:
        #
        #     SELECT * FROM dataset
        #
        # while DuckDB actually reads the Parquet file.
        #
        con.execute("DROP VIEW IF EXISTS dataset")

        con.execute(
            f"""
            CREATE TEMP VIEW dataset AS
            SELECT * FROM read_parquet('{esc}')
            """
        )

        # ----------------------------------------------------
        # STEP 4 — Limit preview results
        # ----------------------------------------------------

        limited_sql = f"SELECT * FROM ({sql}) t LIMIT {limit}"

        cur = con.execute(limited_sql)

        # Extract column names
        cols = [d[0] for d in cur.description]

        rows = cur.fetchall()

        # ----------------------------------------------------
        # STEP 5 — Compute total result size
        # ----------------------------------------------------

        rowcount = con.execute(
            f"SELECT COUNT(*) FROM ({sql}) t"
        ).fetchone()[0]

        # ----------------------------------------------------
        # STEP 6 — Convert rows to dictionaries
        # ----------------------------------------------------

        preview = [
            dict(zip(cols, r))
            for r in rows
        ]

        return cols, preview, rowcount

    finally:

        con.close()